name: skaffold
version:
  source: "github-release:GoogleContainerTools/skaffold"
  exclude_patterns: "(alpha|beta|rc|dev|preview|pre|snapshot|nightly|test|unstable|canary|next|edge|weekly|daily)"
  extract_pattern: '[0-9]+\.[0-9]+\.[0-9]+'
build_type: custom
description: "Easy and repeatable Kubernetes development"

download:
  official_binary: true
  download_url: "https://storage.googleapis.com/skaffold/releases/v{version}/skaffold-{os}-{arch}"
  platforms:
    darwin-x86_64:
      os: "darwin"
      arch: "amd64"
    darwin-arm64:
      os: "darwin"
      arch: "arm64"
    linux-amd64:
      os: "linux"
      arch: "amd64"
    linux-arm64:
      os: "linux"
      arch: "arm64"
security:
  verify_signature: false
  scan_vulnerabilities: true

configure:
  script: |
    # Binary download
    true

build:
  timeout_minutes: 1
  out_of_tree: false
  custom_install: |
    chmod +x skaffold-*
    mkdir -p $PREFIX/bin
    cp skaffold-* $PREFIX/bin/skaffold

dependencies: []
