# golangci-lint configuration (v2.6.2+)
# See: https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck # Check for unchecked errors
    - govet # Vet examines Go source code
    - ineffassign # Detect ineffectual assignments
    - staticcheck # Go static analysis
    - unused # Check for unused code
    - misspell # Check for misspelled words
    - gosec # Security checker
    - gocritic # Go critique
    - revive # Fast linter
    - unconvert # Remove unnecessary type conversions
    - unparam # Unused function parameters
    - gocyclo # Cyclomatic complexity
    - dupl # Duplicate code detection
    - bodyclose # Check HTTP response body is closed
    - nolintlint # Check nolint directives
    - errorlint # Error wrapping checks

formatters:
  enable:
    - gofmt # Check formatting
    - goimports # Check imports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
